export const PATH = {
  home: "/",
  topComic: "/top-comic",
  comic: "/comic",
  search: "/search",
  category: "/category",
  netTruyen: process.env.NEXT_PUBLIC_NHATTRUYEN,
  netTruyenComic: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-tranh`,
  netTruyenSearch: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/tim-truyen`,
  netTruyenFull: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-full`,
  netTruyenGirl: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-con-gai`,
  netTruyenCategory: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/the-loai`,
  netTruyenBoy: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-con-trai`,
  netTruyenFilter: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/tim-truyen-nang-cao`,
};
