export const PATH = {
  home: "/",
  topComic: "/top-comic",
  comic: "/comic",
  search: "/search",
  filter: "/filter",
  category: "/category",
  signUp: "/sign-up",
  signIn: "/sign-in",
  profile: "/profile",
  comment: "/comment",
  follow: "/follow",
  history: "/history",
  manage: "/manage",
  random: "/random",
  girl: "/girl",
  boy: "/boy",
  userManage: "/manage/user",
  commentManage: "/manage/comment",
  changePassword: "/change-password",
  pageNotFound: "/404",
  nhatTruyen: process.env.NEXT_PUBLIC_NHATTRUYEN as string,
  nhatTruyenComic: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-tranh`,
  nhatTruyenSearch: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/tim-truyen`,
  nhatTruyenFull: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-full`,
  nhatTruyenGirl: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-con-gai`,
  nhatTruyenCategory: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/the-loai`,
  nhatTruyenBoy: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/truyen-con-trai`,
  nhatTruyenFilter: `${process.env.NEXT_PUBLIC_NHATTRUYEN}/tim-truyen-nang-cao`,
  projectGithub: "https://github.com/lamhoang1256/netcomic",
};
